{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gateway-auto-listener.fullname" . }}
  labels:
    {{- include "gateway-auto-listener.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "gateway-auto-listener.selectorLabels" . | nindent 6 }}
{{- end }}
